rarities_query = [
    "Ultra Rare",
    "Ultra Parallel Rare",
    "Secret Rare",
    "Extra Secret Rare",
    "Gold Secret Rare",
    "Prismatic Secret Rare",
    "Platinum Secret Rare",
    "Ultimate Rare",
    "Gold Rare",
    "Premium Gold Rare",
    "Collector's Rare",
    "Ghost/Gold Rare",
    "Quarter Century Secret Rare",
    "Starlight Rare",
    "Ghost Rare",
    "10000 Secret Rare"
]

rarities_all = [
    "Common",
    "Rare",
    "Super Rare",
    "Ultra Rare",
    "Ultra Parallel Rare",
    "Duel Terminal Ultra Parallel Rare",
    "Starfoil Rare",
    "Mosaic Rare",
    "Secret Rare",
    "Extra Secret Rare",
    "Gold Secret Rare",
    "Prismatic Secret Rare",
    "Platinum Secret Rare",
    "Ultimate Rare",
    "Gold Rare",
    "Premium Gold Rare",
    "Collectors Rare",
    "Collector's Rare",
    "Ghost/Gold Rare",
    "Quarter Century Secret Rare",
    "Starlight Rare",
    "Ghost Rare",
    "10000 Secret Rare"
]

rarities_short_names = [
    "C",
    "R",
    "SR",
    "UR",
    "UPR",
    "DUPR",
    "SFR",
    "MSR",
    "ScR",
    "EScR",
    "GScR",
    "PScR",
    "PlScR",
    "UtR",
    "GUR",
    "PGR",
    "CR",
    "CR",
    "GGR",
    "QCScR",
    "StR",
    "GR",
    "10000ScR"
]

rarities_short_names_map = {x: y for x, y in zip(rarities_short_names, rarities_all)}