name: build-and-release

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    steps: 
    
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true
      
      
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
          
      - uses: game-ci/unity-builder@v2.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: src/BinderSim
          
          
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
          
          
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
        
      - name: Release
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          target-folder: ${{ env.RELEASE_VERSION }}
